services:
  - type: web
    name: stage
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: MYSQL_HOST
        value: localhost
      - key: MYSQL_USER
        value: root
      - key: MYSQL_PASSWORD
        value: MedYahya47!!
      - key: MYSQL_DB
        value: data_upload
      - key: FLASK_SECRET
        generateValue: true
